-name: Demo on Ignore errors
  hosts: all
  tasks:
    - name: Checking whether tomcat is running or not
      ansible.builtin.shell: ps -ef | grep tomcat | grep -v grep
      register: OUT
      ignore_errors: yes

    - name: Starting Tomcat
      ansible.builtin.debug:
      msg: Starting Tomcat