- name: Demo on privilege escalation
  hosts: all
  become: yes                                              #executing whole playbook as root user (become-sudo in bash)
  tasks:
    - name: Executing shell command
      ansible.builtin.shell: id
      register: OUT

    - name: Displaying output
      ansible.builtin.debug:
      msg: "{{OUT.stdout}}"