- name: Installing python and dependecies
ansible.builtin.yum
  name: "{{item}}"
  state: installed
loop:
  - python36
  -gcc
  -python3-devel

- name: Creating Roboshop user
  include_role:
    name: common
    tasks_from: create-user

- name: Test Printout
  ansible.builtin.debug
    msg: "{{APPUSER_INFO}}"
 
- name: Updating the UID in the ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{APPUSER_INFO.uid}}

- name: Updating the GID in the ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: uid = {{APPUSER_INFO.group}}


- name: Downloading and extracting the component
  include_role:
    name: common
    tasks_from: download

- name: Installing python dependencies
  ansible.builtin.pip
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3.3
    