- name: Downloading and extracting the Component
  ansible.builtin.unarchive:
    src:  https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    #src: https://stans-proj-code.s3.amazonaws.com/{{COMPONENT}}.zip                       #after creating bucket in aws
    dest: /tmp
    remote_src: yes 


- name: Cleanup of old content
  ansibile.builtin.file:
    path:/home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: yes
  

- name: Copy files to the roboshop home directory
  ansible.builtin.copy
  src: /tmp/{{COMPONENT}}-main
  dest: /home/{{APPUSER}}/{{$COMPONENT}}/
  remote_src: yes 
  owner: "{{APPUSER}}"
  group: "{{APPUSER}}"
ignore_errors: yes